version: '3.8'

services:
  frontend:
    image: node:20-alpine 
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
